### ISSUE TITLE
Not a issue a doubt

### ISSUE THREAD

**Issue by bolavefasfas** [daggergad7/heroku-aria-5-cloud-syncs#4]
can you add up more description of what the bot does like does it sync all the 5 drives provided in rclone config for example i manually upload 1 file in say 3 rd drive then it will automatically be synced in the rest of 4 drives is this what bot does ???

**Comment by daggergad7** [comment]
Nope, its a aria2 downloader + ariaNG frontend which downloads the file on the server storage and then via rclone uploads it to the specified clouds.
If you want to sync (as mentioined in the question), you have to set up a static file hosting and tell aria to download your file - once that is done rclone will upload it to all of the 5 drives.
Please close this issue if this answers your question, or else ask more questions. Thanks!
